### ISSUE TITLE
Interpolating Satellite Position

### ISSUE THREAD

**Issue by thkruz** [ajmas/StuffInSpace#28]
updateSatellites is only being called at init, selected, hover, and onmessage. This is absolutely the most efficient method, but then the satellites "jump" about every second. I'd recommend either lowering the throttle on the satCruncherWorker to 16ms or doing something like this every frame:

```ts
// Pseudo code
sat.position[0] += sat.velocity * dt;
```

**Comment by ajmas** [comment]
For the satCruncherWorker I had lowered the refresh rate to avoid a CPU hit, but I have since made a compromise by pausing the satCruncherWorker, if the window is not in view. The side effect is that there will be a drift, relative to the amount of time the window was out of view.

Short term, for ease I'll increase the satCruncherWorker to 16ms, but will need to work out how to deal with the drift problem in a separate issue.

I do want to be finding the right compromise between resource hit and processing accuracy.

**Comment by ajmas** [comment]
I have just pushed a change and I have made the frequency at which the worker does it work configurable. See in `public/config.json`.

**Comment by thkruz** [comment]
> I have since made a compromise by pausing the satCruncherWorker, if the window is not in view. 

Great idea! I've never really thought about that obvious waste of resources.

**Comment by ajmas** [comment]
Merged changes - thanks
